---
title: "GroupProject"
output: html_document
---

```{r}
library(tidyverse)
library(broom)
library(scales)
library(lubridate)
library(bigrquery)
```

```{r}
bq_projects
project_id <- "weighty-nation-450808-j5"

query <- "
SELECT
  fullVisitorId,  -- Unique visitor ID
  visitId,        -- Unique session ID
  _TABLE_SUFFIX AS table_date,  -- Extracts the date from the table name
  date,          -- Session date
  trafficSource.source AS traffic_source,  -- Where traffic came from
  trafficSource.medium AS traffic_medium,  -- Medium (organic, cpc, referral, etc.)
  trafficSource.campaign AS campaign_name, -- Campaign name (if applicable)
  device.deviceCategory AS device_category,  -- Desktop, mobile, tablet
  device.operatingSystem AS operating_system, 
  device.browser AS browser,
  totals.pageviews AS total_pageviews,  -- Number of pages viewed
  totals.timeOnSite AS total_time_on_site,  -- Time spent on site
  totals.bounces AS bounces,  -- Bounce count (1 = bounced)
  totals.transactions AS transactions,  -- Number of purchases made
  totals.totalTransactionRevenue / 1e6 AS revenue,  -- Revenue (converted to dollars)
  totals.sessionQualityDim AS session_quality,  -- Engagement score
  geoNetwork.country AS user_country  -- User’s country
FROM `bigquery-public-data.google_analytics_sample.ga_sessions_*`
WHERE totals.pageviews IS NOT NULL  -- Filter out empty sessions
ORDER BY revenue DESC
"
bq_data <- bq_project_query(project_id, query)
google_store <- bq_table_download(bq_data)

```
```{r}
google_store
google_store$date <- ymd(google_store$table_date)
google_store$table_date <- NULL
google_store$bounces <- replace_na(google_store$bounces, 0)
```


```{r}
table(google_store$bounces)
```

