---
title: "Holidays"
output: html_document
---

```{r}
library(lubridate)
library(jsonlite)
library(countrycode)
library(tidyverse)

google_store <- read_csv("data/google_store.csv")
google_store <- google_store %>% 
  mutate(
    purchase = ifelse(is.na(revenue) | revenue == 0, 0, 1))
```

```{r}
google_store$date <- ymd(google_store$date)

date_place <- google_store %>%
  distinct(date, user_country)

date_place <- date_place %>%
  mutate(country_code = 
           countrycode(
             user_country, "country.name", "iso2c", warn = FALSE
           ))

get_holidays <- function(year, country_code) {
  url <- paste0("https://date.nager.at/api/v3/publicholidays/", year, "/", country_code)
  
  # Try fetching the data, handle errors
  tryCatch({
    holidays <- fromJSON(url)
    #print(head(holidays))
    holidays$date <- ymd(holidays$date)
    return(holidays$date)
  }, error = function(e) {
    #message("Error fetching holidays for ", country_code, " in ", year, ": ", e$message)
    return(as.Date(character()))  # Return empty date vector on failure
  })
}

mark_holidays <- function(df, country_code){
  holiday_list16 <- get_holidays(2016, country_code)
  holiday_list17 <- get_holidays(2017, country_code)
  holiday_list18 <- get_holidays(2018, country_code)
  holiday_list <- c(holiday_list16, holiday_list17, holiday_list18)
  #holiday_list %>% print()
  indices <- which(df$country_code == country_code & !is.na(df$date))
  
  # Ensure we're not assigning NA values
  df$is_holiday[indices] <- df$date[indices] %in% holiday_list
  return(df)
}

date_place$is_holiday <- FALSE

for (code in unique(date_place$country_code)){
  date_place <- mark_holidays(date_place, code)
}

write.csv(date_place, "data/date_place.csv", row.names = FALSE)

```


```{r}
google_store$date <- ymd(google_store$date)
google_store <- left_join(google_store, date_place, by=c("date", "user_country"))

daily_stats <- google_store %>%
  group_by(date, user_country) %>%
  summarize(
    total_revenue = sum(revenue, na.rm=TRUE),
    average_revenue = mean(revenue, na.rm = TRUE),
    bounce_rate = mean(bounces, na.rm = TRUE),
    total_visits = n(),
    total_sales = sum(purchase),
    is_holiday = first(is_holiday), # Carry over the is_holiday value
    .groups = "drop"
    )

find_days_till_holiday <- function(df, country, current_date) {
  holiday_dates <- df %>%
    filter(user_country == country,
           date >= current_date,
           is_holiday == TRUE) %>%
    arrange(date) %>%
    head(1)

  if (nrow(holiday_dates) > 0) {
    next_holiday <- holiday_dates$date[1]
    return(as.numeric(difftime(next_holiday, current_date, units = "days")))
  } else {
    return(NA) 
  }
}

daily_stats <- daily_stats %>%
  rowwise() %>%
  mutate(
    days_till_holiday = find_days_till_holiday(daily_stats, user_country, date)
  ) %>%
  ungroup()

write.csv(daily_stats, "data/daily_stats.csv", row.names = FALSE)
daily_stats
```
